### ISSUE TITLE
error message:"The application bundle does not contains valid identifier"

### ISSUE THREAD

**Issue by madik** [kstenerud/iOS-Universal-Framework#17]
Hi!

I started to use your solution today, very useful. I made everything, you wrote, I created a "fake" framework, build in releae configuration. Then I drag&drop the xy.embeddedframework folder to my project, and everything work (I can use xib files, etc..). But sometimes I got such error message, when I try to run the app on device. Most recent in cases, when I modify something in the framework, then I delete the references from the "main" project, and I add again.
In such situations, I couldn't do anything, I have to create a new project. This is very annoying. What i'm missing?

**Comment by zeshanmusawar** [comment]
Please Try this 
https://stackoverflow.com/questions/37750186/the-application-bundle-does-not-contain-a-valid-identifier/39450461
Thanks
