### ISSUE TITLE
Using framework classes in NIB files

### ISSUE THREAD

**Issue by kringelbach** [kstenerud/iOS-Universal-Framework#9]
When using a class from a Real Framework in a NIB, I get the following error when running the application:

Unknown class MyFrameworkClass in Interface Builder file.

MyFrameworkClass is included in the NIB file as an Object with Custom Class set to MyFrameworkClass. The actual case is that I have implemented a UITextFieldDelegate that is attached to a UITextField. I.e. I do not need any references to it in my source code. The problem persists even if I connect it to an IBOutlet in my View Controller.

If I use the class from my source code, either by allocating an instance or by implementing _keepAtLinkTime as described in http://stackoverflow.com/questions/1725881/unknown-class-myclass-in-interface-builder-file-error-at-runtime everything works fine. This is however not a user friendly interface to the users of the framework.

Are there any better ways to ensure that all framework items used in a NIB is included in the binary? A solution that always includes the entire framework in the binary is not desirable either.

**Comment by Niko-r** [comment]
Hi,

Almost 5 years after your answer, I just want to thank you @kstenerud for sharing your solution with `forceLinkerLoad_` . 

This was the solution to my issue, I found it nowhere else from here, and you deserve my thanks.

So thank you again ! :-)

**Comment by paleozogt** [comment]
Another possibility is to use Xcode's `Perform Single-Object Prelink`
